iut_dossiers:
    resource: "@IutDossiersBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
homepage:
    path: /
    defaults: { _controller: AppBundle:Default:index }
