Iut\DossiersBundle\Entity\ListeMailsDossier:
    type: entity
    table: null
    repositoryClass: Iut\DossiersBundle\Repository\ListeMailsDossierRepository
    id:
        dossierId:
            type: integer
            id: true
            generator:
                strategy: NONE
        mailId:
            type: integer
            id: true
            generator:
                strategy: NONE
    lifecycleCallbacks: {  }
