Iut\DossiersBundle\Entity\ListeFormationsVacataire:
    type: entity
    table: null
    repositoryClass: Iut\DossiersBundle\Repository\ListeFormationsVacataireRepository
    id:
        vacataireId:
            type: integer
            id: true
            generator:
                strategy: NONE
        formationId:
            type: integer
            id: true
            generator:
                strategy: NONE
    lifecycleCallbacks: {  }
