Iut\DossiersBundle\Entity\Piece:
    type: entity
    table: null
    repositoryClass: Iut\DossiersBundle\Repository\PieceRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        libelle:
            type: string
            length: '50'
    lifecycleCallbacks: {  }
