<?php

namespace Iut\DossiersBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * DossierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DossierRepository extends EntityRepository {

    public function findAll() {
        return $this->createQueryBuilder("d")
            ->leftJoin("d.vacataire", "vacataire")
            ->leftJoin("d.pieces", "pieces")
            ->leftJoin("d.etat", "etat")
            ->addSelect("vacataire")
            ->addSelect("pieces")
            ->addSelect("etat")
            ->getQuery()->getResult();
    }

    public function getLastRelance() {
        return $this->createQueryBuilder("d")
            ->leftJoin("d.mail", "mails")
            ->select("MAX(d.mail)")
            ->getQuery()
            ->getSingleResult();
    }

}
