<?php

namespace Iut\DossiersBundle\Repository;

/**
 * ListeFormationsVacataireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ListeFormationsVacataireRepository extends \Doctrine\ORM\EntityRepository
{
}
