<?php

namespace Iut\DossiersBundle\Repository;

/**
 * ListeMailsDossierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ListeMailsDossierRepository extends \Doctrine\ORM\EntityRepository
{
}
