<?php

namespace Iut\DossiersBundle\Repository;

/**
 * ListePiecesDossierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ListePiecesDossierRepository extends \Doctrine\ORM\EntityRepository
{
}
