<?php

namespace Iut\DossiersBundle\Repository;

/**
 * MailRelanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MailRelanceRepository extends \Doctrine\ORM\EntityRepository
{
}
