<?php

namespace Iut\DossiersBundle\Repository;

/**
 * ModeleMailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModeleMailRepository extends \Doctrine\ORM\EntityRepository {

}
