<?php

namespace Iut\DossiersBundle\Repository;

/**
 * VacataireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VacataireRepository extends \Doctrine\ORM\EntityRepository {

    public function findAllDossiersAndFormations() {
        return $this->createQueryBuilder('v')
            ->leftJoin('v.formations', 'formations')
            ->leftJoin('v.dossiers', 'dossiers')
            ->addSelect("formations")
            ->addSelect('dossiers')
            ->getQuery()
            ->getResult();
    }

}
