homepage:
    path: /dossiers
    defaults: { _controller: IutDossiersBundle:Default:index }

#pageNotFound:
#    path:  /{path}
#    defaults: { _controller: IutDossiersBundle:PageNotFound:pageNotFound, path: '' }
#    requirements:
#        path: .*
        
ajouterVacataire: 
    path: /dossiers/vacataire/ajouter
    defaults: { _controller: IutDossiersBundle:Default:ajouterVacataire }

modifierVacataire:
    path: /dossiers/vacataire/modifier/{id}
    defaults: { _controller: IutDossiersBundle:Default:ajouterVacataire }
    requirements:
        id: \d+

supprimerVacataire:
    path: /dossiers/vacataire/supprimer/{id}
    defaults: { _controller: IutDossiersBundle:Default:supprimerVacataire }
    requirements:
        id: \d+

ajouterModeleMail:
    path: /dossiers/modeles_mails/ajouter
    defaults: { _controller: IutDossiersBundle:Default:ajouterModeleMail }


consulterModeleMail:
    path: /dossiers/modeles_mails
    defaults: { _controller: IutDossiersBundle:Default:consulterModeleMail }

modifierModeleMail:
    path: /dossiers/modeles_mails/modifier
    defaults: { _controller: IutDossiersBundle:Default:modifierModeleMail }

afficherModeleMail:
    path: /dossiers/modeles_mails/afficher/{id}
    defaults: { _controller: IutDossiersBundle:Default:afficherModeleMail }
    requirements:
        id: \d+

supprimerModeleMail:
    path: /dossiers/modeles_mails/supprimer/{id}
    defaults: { _controller: IutDossiersBundle:Default:supprimerModeleMail }
    requirements:
        id: \d+
