homepage:
    path: /dossiers
    defaults: { _controller: IutDossiersBundle:Default:index }

#pageNotFound:
#    path:  /{path}
#    defaults: { _controller: IutDossiersBundle:PageNotFound:pageNotFound, path: '' }
#    requirements:
#        path: .*
        
ajouterVacataire: 
    path: /dossiers/vacataire/ajouter
    defaults: { _controller: IutDossiersBundle:Default:ajouterVacataire }
    
supprimerVacataire: 
    path: /dossiers/vacataire/supprimer/{$id}
    defaults: { _controller: IutDossiersBundle:Default:supprimerVacataire }
    requirements:
        id: \d+