homepage:
    path: /dossiers
    defaults: { _controller: IutDossiersBundle:Vacataire:afficherListeVacataires }

 ###################
 #    Vacataire    #
 ###################

vacataire_liste:
    path: /dossiers/vacataire/
    defaults: { _controller: IutDossiersBundle:Vacataire:afficherListeVacataires }

vacataire_ajouter:
    path: /dossiers/vacataire/ajouter
    defaults: { _controller: IutDossiersBundle:Vacataire:ajouterVacataire, id:-1 }

vacataire_modifier:
    path: /dossiers/vacataire/modifier/{id}
    defaults: { _controller: IutDossiersBundle:Vacataire:ajouterVacataire }
    requirements:
        id: \d+

vacataire_supprimer:
    path: /dossiers/vacataire/supprimer/{id}
    defaults: { _controller: IutDossiersBundle:Vacataire:supprimerVacataire }
    requirements:
        id: \d+

 ###################
 # PieceController #
 ###################

piece_ajouter:
    path: /dossiers/piece/ajouter
    defaults: { _controller: IutDossiersBundle:Piece:ajouterPiece}
    
piece_supprimer:
    path: /dossiers/piece/supprimer/{id}
    defaults: { _controller: IutDossiersBundle:Piece:supprimerPiece }
    requirements:
        id: \d+

piece_liste:
    path: /dossiers/piece
    defaults: { _controller: IutDossiersBundle:Piece:listePieces }

 ###################
 #  MailController #
 ###################

modele-mail_liste:
    path: /dossiers/modele-mail
    defaults: { _controller: IutDossiersBundle:Mail:listeModelesMail }

modele-mail_afficher:
    path: /dossiers/modele-mail/afficher/{id}
    defaults: { _controller: IutDossiersBundle:Mail:afficherModeleMail, id: -1}
    requirements:
        id: \d+

modele-mail_ajouter:
    path: /dossiers/modele-mail/ajouter/{id}
    defaults: { _controller: IutDossiersBundle:Mail:ajouterModeleMail, id: -1 }

modele-mail_modifier:
    path: /dossiers/modeles-mails/modifier/{id}
    defaults: { _controller: IutDossiersBundle:Mail:ajouterModeleMail }
    requirements:
        id: \d+

modele-mail_supprimer:
    path: /dossiers/modele-mail/supprimer/{id}
    defaults: { _controller: IutDossiersBundle:Mail:supprimerModeleMail }
    requirements:
        id: \d+
    
dossier_relancer:
    path: /dossiers/relancer/{dossierId}
    defaults: { _controller: IutDossiersBundle:Mail:envoyerRelance, dossierId: 1}
    requirements:
        dossierId: \d+

 #####################
 # DossierController #
 #####################

dossier_ajouter:
    path: /dossiers/ajouter
    defaults: { _controller: IutDossiersBundle:Dossier:ajouterDossier }
    
    
 #######################
 # FormationController #
 #######################
formation_ajouter:
    path: /dossiers/formation/ajouter
    defaults: { _controller: IutDossiersBundle:Formation:ajouterFormation}
    
formation_supprimer:
    path: /dossiers/formation/supprimer/{id}
    defaults: { _controller: IutDossiersBundle:Formation:supprimerFormation }
    requirements:
        id: \d+

formation_liste:
    path: /dossiers/formation
    defaults: { _controller: IutDossiersBundle:Formation:listeFormations }