homepage:
    path: /dossiers
    defaults: { _controller: IutDossiersBundle:Vacataire:index }

#pageNotFound:
#    path:  /{path}
#    defaults: { _controller: IutDossiersBundle:PageNotFound:pageNotFound, path: '' }
#    requirements:
#        path: .*
        
ajouterVacataire: 
    path: /dossiers/vacataire/ajouter
    defaults: { _controller: IutDossiersBundle:Vacataire:ajouterVacataire, id:-1 }

modifierVacataire:
    path: /dossiers/vacataire/modifier/{id}
    defaults: { _controller: IutDossiersBundle:Vacataire:ajouterVacataire }
    requirements:
        id: \d+

supprimerVacataire:
    path: /dossiers/vacataire/supprimer/{id}
    defaults: { _controller: IutDossiersBundle:Vacataire:supprimerVacataire }
    requirements:
        id: \d+

ajouterModeleMail:
    path: /dossiers/modeles_mails/ajouter
    defaults: { _controller: IutDossiersBundle:Mail:ajouterModeleMail }


afficherListeModelesMail:
    path: /dossiers/modeles_mails
    defaults: { _controller: IutDossiersBundle:Mail:listeModelesMail }

modifierModeleMail:
    path: /dossiers/modeles_mails/modifier
    defaults: { _controller: IutDossiersBundle:Mail:modifierModeleMail }

afficherModeleMail:
    path: /dossiers/modeles_mails/afficher/{id}
    defaults: { _controller: IutDossiersBundle:Mail:afficherModeleMail }
    requirements:
        id: \d+

supprimerModeleMail:
    path: /dossiers/modeles_mails/supprimer/{id}
    defaults: { _controller: IutDossiersBundle:Mail:supprimerModeleMail }
    requirements:
        id: \d+
relancerDossier:
    path: /dossiers/relancer/{dossierId}
    defaults: { _controller: IutDossiersBundle:Mail:envoyerMail, dossierId: -1 }
    requirements:
        dossierId: \d+
